version: "3"

services:
  db:
    image: mysql:8.4
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_ROOT_USER: root
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db:/home/user/decoya/db
      - ./db/ssl:/etc/mysql/
    restart: always
    networks:
      - decoyanetwork
  app:
    build: ./app
    image: ubuntu:24.04
    working_dir: /home/user/decoya
    container_name: app
    # command: tail -f /dev/null
    ports:
      - "2222:22"
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_ROOT_USER: root
    env_file:
      - .env
    volumes:
      - ./app:/home/user/decoya/app
    networks:
      - decoyanetwork
    depends_on:
      - db

  ########################################################################################################
  # Bonus challange part - write both in python and bash. Another bash solution in ./db/ & /app/ Dockerfile
  ######################################################################################################## 
  # Kept one for simplicity on install 
  create-table:
    image: python:latest
    container_name: create_table
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_ROOT_USER: root
    env_file:
      - .env
    volumes:
      - /home/user/decoya/db/create_users_table.py:/home/user/decoya/create_users_table.py
    networks:
      - decoyanetwork
    depends_on:
      - db
    command: >
      bash -c "python3 -m venv /venv &&
              source /venv/bin/activate &&
              pip install mysql-connector-python &&
              python /home/user/decoya/create_users_table.py"

volumes:
  mysql_data:

networks:
  decoyanetwork:
    driver: bridge